# Generated by Django 3.1.4 on 2021-05-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emprea',
            new_name='Empresa',
        ),
    ]
