# Generated by Django 3.1.4 on 2021-05-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210508_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa_ESG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('sector', models.CharField(max_length=100, null=True)),
                ('ESG', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='DEBT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='INSIDERS',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='PER',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ROA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='TRENDS',
            field=models.FloatField(null=True),
        ),
    ]
